"use client";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { useStore } from "@/lib/store";
import type { Listing } from "@/lib/types";
import { ListingImage } from "./ListingImage";
import { Ago } from "./Ago";
import { CITIES } from "@/data/geo";
import { CATEGORIES } from "@/data/taxonomy";
import { tl } from "@/lib/format";
import { EditorialArrow } from "./EditorialMedia";
import { useMotionOK } from "./Motion";
import { ScrollExperience } from "./ScrollExperience";
import {useRouter} from "next/navigation";

type Offer={listingId:string;amount:number;note:string};
type ClosetState={following:string[];offers:Offer[]};
const KEY="ozilan.closets.v1";
const conditions=["Sıfır","Az kullanılmış","İyi","Yıpranmış","Arızalı / parçalık"];
export default function ResaleFeed(){
  const motion=useMotionOK();
  const {pool,sellers,ready,toggleFav,isFav,state,live,me,openThread,send}=useStore();
  const router=useRouter();
  const [sending,setSending]=useState(false);
  const [tab,setTab]=useState("discover"),[category,setCategory]=useState(""),[city,setCity]=useState(""),[condition,setCondition]=useState(""),[query,setQuery]=useState(""),[sort,setSort]=useState("new"),[max,setMax]=useState("");
  const [closet,setCloset]=useState<string|null>(null),[limit,setLimit]=useState(24);
  const [filtersOpen,setFiltersOpen]=useState(false);
  const resultsRef=useRef<HTMLElement>(null);
  const [local,setLocal]=useState<ClosetState>({following:[],offers:[]});
  const [loaded,setLoaded]=useState(false),[message,setMessage]=useState("");
  const [offer,setOffer]=useState<Listing|null>(null),[amount,setAmount]=useState(0),[showOffers,setShowOffers]=useState(false);
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{try{const v=JSON.parse(localStorage.getItem(KEY)??"null");if(v)setLocal({following:Array.isArray(v.following)?v.following.filter((id:unknown)=>typeof id==="string"):[],offers:Array.isArray(v.offers)?v.offers.filter((o:Offer)=>o&&typeof o.listingId==="string"&&Number.isFinite(o.amount)&&o.amount>0&&typeof o.note==="string"):[]});}catch{}setLoaded(true);},[]);
  useEffect(()=>{const d=dialog.current;if((offer||showOffers)&&!d?.open)d?.showModal();else if(!offer&&!showOffers&&d?.open)d.close();},[offer,showOffers]);
  useEffect(()=>setLimit(24),[tab,category,city,condition,query,sort,max,closet]);
  function persist(next:ClosetState){try{localStorage.setItem(KEY,JSON.stringify(next));setLocal(next);setMessage("");return true;}catch{setMessage("Tarayıcı depolaması kullanılamıyor; değişiklik kaydedilmedi.");return false;}}
  const all=useMemo(()=>pool.filter(l=>l.cat==="ikinci-el"&&l.status==="active"),[pool]);
  const categories=CATEGORIES.find(c=>c.slug==="ikinci-el")!.subs;
  const closets=useMemo(()=>[...new Set(all.map(l=>l.sellerId))].slice(0,8),[all]);
  const results=useMemo(()=>{
    const text=query.trim().toLocaleLowerCase("tr");
    if(tab==="near"&&!city)return [];
    return all.filter(l=>(!category||l.sub===category)&&(!city||l.city===city)&&(!condition||l.attrs.durum===condition)&&(!text||`${l.title} ${l.pathLabels?.join(" ")}`.toLocaleLowerCase("tr").includes(text))&&(!max||l.price<=Number(max))&&(!closet||l.sellerId===closet)&&(tab!=="saved"||state.favorites.includes(l.id))&&(tab!=="following"||local.following.includes(l.sellerId))).sort((a,b)=>sort==="price"?a.price-b.price:sort==="price-desc"?b.price-a.price:b.createdAt-a.createdAt);
  },[all,category,city,condition,query,max,closet,tab,sort,state.favorites,local.following]);
  function reset(){setCategory("");setCity("");setCondition("");setQuery("");setMax("");setCloset(null);setTab("discover");}
  function openCloset(id:string){reset();setCloset(id);}
  function discoverCategory(value:string){reset();setCategory(value);resultsRef.current?.scrollIntoView({behavior:motion?"smooth":"instant",block:"start"});}
  function follow(id:string){persist({...local,following:local.following.includes(id)?local.following.filter(x=>x!==id):[...local.following,id]});}
  function prepareOffer(l:Listing){setOffer(l);setShowOffers(false);setAmount(Math.max(1,Math.round(l.price*.9)));setMessage("");}
  async function saveOffer(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!offer||sending)return;const f=new FormData(e.currentTarget);const next={listingId:offer.id,amount:Number(f.get("amount")),note:String(f.get("note")??"").trim()};if(!Number.isFinite(next.amount)||next.amount<=0||next.amount>offer.price){setMessage("Teklif, ilan fiyatından yüksek veya sıfır olamaz.");return;}
    if(live){if(!me){router.push("/giris/?sonra=%2Fakis%2F");return;}setSending(true);const thread=await openThread(offer.id);if(thread&&await send(thread,`Teklifim: ${tl(next.amount)}. ${next.note}`)){setOffer(null);router.push(`/mesajlar/?gorusme=${thread}`);}setSending(false);return;}
    if(persist({...local,offers:[next,...local.offers.filter(o=>o.listingId!==offer.id)].slice(0,100)})){setOffer(null);setShowOffers(true);setMessage("Teklif taslağın saklandı. Satıcıya gönderilmedi.");}}
  const selectedSeller=closet?sellers[closet]:null;
  return <div className="resale-feed"><ScrollExperience/>
    <div className="resale-intro resale-editorial-intro">
      <div className="resale-intro-copy"><p className="market-eyebrow">OZBİRARADA / İKİNCİ EL</p><h1>İyi eşyalar.<br/><em>Yeni sahipler.</em></h1><p>Bir dolapta bekleyen, başka bir hayatın en sevdiği parçası olabilir.</p><div className="resale-intro-actions"><Link href="/ilan-ver/" className="market-primary">Dolabına ürün ekle <EditorialArrow/></Link>{live?<Link href="/mesajlar/">Teklif görüşmelerim ↗</Link>:<button onClick={()=>{setOffer(null);setShowOffers(true);setMessage("");}}>Teklif taslaklarım {loaded&&local.offers.length>0?`(${local.offers.length})`:""} ↗</button>}</div><small>{live?"Gerçek ilanlar · Tekliflerini satıcıya mesaj olarak iletebilirsin.":"Örnek ilan akışı · Takiplerin ve taslakların bu cihazda saklanır."}</small><div className="resale-edition"><span>AZ KULLANILDI.<br/>DAHA ÇOK SEVİLECEK.</span><span aria-hidden="true">↘</span></div></div>
      <div className="resale-intro-art" aria-hidden="true"><span>YENİDEN.</span><svg viewBox="0 0 340 270"><path d="m104 93 39-35 31 12 30-12 44 35-35 39v108H135V132Z" fill="#e9ddd5"/><path d="M145 62q27 52 58 0" fill="none" stroke="#b8a296" strokeWidth="8"/><path d="M154 147h40m-40 15h28" stroke="#b89c91" strokeWidth="4"/><path d="m212 117 42-10 33 55-13 83-63-11Z" fill="#7d9fba"/><path d="m230 130 25-5 10 27-16 46" fill="none" stroke="#d1e3eb" strokeWidth="3"/></svg><span className="resale-tag">SEVİLEREK KULLANILDI ↗</span></div>
      <div className="resale-cover-categories" role="group" aria-label="İkinci el kategorileri">{categories.map(c=><button key={c.slug} aria-pressed={category===c.slug} onClick={()=>discoverCategory(c.slug)}>{c.label}<EditorialArrow/></button>)}</div>
    </div>
    {message&&!offer&&!showOffers&&<p className="market-storage-error" role="status">{message}</p>}<section ref={resultsRef} className="resale-content" aria-label="İkinci el keşif akışı">
      <div className="resale-tabs" role="group" aria-label="Akış türü">{[["discover","Senin için"],["near","Yakınımda"],["following","Takip ettiklerim"],["saved","Beğendiklerim"]].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>{setTab(key);setCloset(null);}}>{label}</button>)}<Link href="/arama/?k=ikinci-el">Detaylı ara ↗</Link></div>
      <div className="closet-stories"><button className={!closet?"selected":""} onClick={()=>setCloset(null)}><span>∞</span><small>Tüm dolaplar</small></button>{closets.map(id=><button className={closet===id?"selected":""} key={id} onClick={()=>{setCloset(id);setTab("discover");setCity("");setCategory("");setQuery("");setCondition("");setMax("");}}><span>{sellers[id]?.name.slice(0,1)??"O"}</span><small>{sellers[id]?.name.split(" ")[0]??"Satıcı"}</small></button>)}</div>
      {selectedSeller&&<div className="closet-profile"><div><p className="market-eyebrow">SATICININ DOLABI</p><h2>{selectedSeller.name}</h2><p>{all.filter(l=>l.sellerId===closet).length} ürün · {selectedSeller.city}</p></div><button disabled={!loaded} className="market-primary" onClick={()=>follow(closet!)}>{local.following.includes(closet!)?"Takibi bırak":"Dolabı takip et"}</button><button aria-label="Dolap filtresini kaldır" onClick={()=>setCloset(null)}>×</button></div>}
      <div className="market-filter-shell resale-filters"><div className="market-search-row"><label><span>Ne arıyorsun?</span><input type="search" placeholder="Çanta, ayakkabı, kulaklık…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label><span>Sıralama</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Yeni eklenenler</option><option value="price">En düşük fiyat</option><option value="price-desc">En yüksek fiyat</option></select></label></div><div className="market-category-pills"><button aria-pressed={!category} onClick={()=>setCategory("")}>Tümü</button>{categories.map(c=><button key={c.slug} aria-pressed={category===c.slug} onClick={()=>setCategory(c.slug)}>{c.label}</button>)}</div><div className="resale-filter-tools"><span>{[city,condition,max?`En fazla ${max} TL`:""].filter(Boolean).join(" · ")||"Aradığın parçaya biraz daha yaklaş."}</span><button aria-expanded={filtersOpen||tab==="near"} aria-controls="resale-extra-filters" onClick={()=>{if(tab==="near")setTab("discover");setFiltersOpen(!(filtersOpen||tab==="near"));}}>Filtreler <span>{filtersOpen||tab==="near"?"−":"＋"}</span></button></div>{(filtersOpen||tab==="near")&&<div id="resale-extra-filters" className="market-secondary-filters"><label><span>{tab==="near"?"Yakınındaki ilanlar için şehir seç":"Şehir"}</span><select value={city} onChange={e=>setCity(e.target.value)}><option value="">{tab==="near"?"Şehrini seç":"Tüm Türkiye"}</option>{CITIES.map(c=><option key={c}>{c}</option>)}</select></label><label><span>Ürün durumu</span><select value={condition} onChange={e=>setCondition(e.target.value)}><option value="">Tüm durumlar</option>{conditions.map(c=><option key={c}>{c}</option>)}</select></label><label><span>En yüksek fiyat (TL)</span><input type="number" min="0" value={max} onChange={e=>setMax(e.target.value)} placeholder="Sınır yok"/></label><button className="market-reset" onClick={reset}>Sıfırla</button></div>}</div>
      <div className="resale-result-line"><p>{closet?"Bu dolaptan seçtiklerin":tab==="near"&&city?`${city} içindeki ilanlar`:"Yeni sahibini bekleyenler"}</p><span aria-live="polite">{results.length} ürün</span></div>
      {!results.length?<div className="market-empty"><h3>{tab==="near"&&!city?"Yakınındaki keşifler için şehrini seç.":tab==="following"&&!local.following.length?"İlk dolabını takip et.":tab==="saved"?"Beğendiğin parçalar burada biriksin.":"Bu seçimde bir ürün bulamadık."}</h3><p>{tab==="near"?"Şehir bilgisiyle eşleştiriyoruz; konum izni veya kesin konum gerekmiyor.":"Dolaplara göz atabilir, filtreleri değiştirebilir veya akışa geri dönebilirsin."}</p><button className="market-primary" onClick={reset}>Akışı keşfet</button></div>:<div className="resale-grid">{results.slice(0,limit).map(l=><article className="resale-card" key={l.id}><button className="resale-seller" onClick={()=>openCloset(l.sellerId)}><span>{sellers[l.sellerId]?.name.slice(0,1)??"O"}</span>{sellers[l.sellerId]?.name??"Satıcı"}<span>Dolabı ↗</span></button><div className="resale-picture"><Link href={`/ilan/?id=${l.id}`} aria-label={`${l.title} ilanını incele`}><ListingImage listing={l} className="aspect-square w-full"/></Link><button disabled={!ready} onClick={()=>toggleFav(l.id)} aria-label={`${l.title} ${isFav(l.id)?"beğenmekten vazgeç":"beğen"}`} aria-pressed={isFav(l.id)}>{isFav(l.id)?"♥":"♡"}</button><span>{String(l.attrs.durum??"Durum belirtilmemiş")}</span></div><div className="resale-card-copy"><Link href={`/ilan/?id=${l.id}`}><h3>{l.title}</h3></Link><p>{l.district} · {l.city}</p><div><strong>{tl(l.price)}</strong><span><Ago ts={l.createdAt}/></span></div>{l.price>0?<button className="resale-offer" onClick={()=>prepareOffer(l)}>Teklif hazırla ↗</button>:<Link className="resale-offer" href={`/ilan/?id=${l.id}`}>İlanı incele ↗</Link>}</div></article>)}</div>}
      {results.length>limit&&<button className="resale-more" onClick={()=>setLimit(n=>n+24)}>Daha fazla keşfet <span>＋</span></button>}
      <div className="resale-endnote"><strong>Kullanılmaya değer. Yeniden keşfetmeye değer.</strong><p>{live?"Akış yayındaki gerçek ikinci el ilanlarından oluşur. Tekliflerin satıcıya mesaj olarak gider; platform ödeme, kargo veya stok garantisi sunmaz.":"Akış örnek ikinci el ilanlarına bağlıdır. Örnek görseller illüstrasyondur; stok, ödeme, kargo ve canlı mesajlaşma bu keşif sürümünde bulunmaz."}</p></div>
    </section>
    <dialog ref={dialog} className="market-dialog" aria-label={offer?"Teklif hazırla":"Teklif taslaklarım"} onCancel={()=>{setOffer(null);setShowOffers(false);}} onClick={e=>{if(e.target===e.currentTarget){setOffer(null);setShowOffers(false);}}}><div className="market-dialog-inner"><div className="market-dialog-heading"><h2>{offer?"Bir teklif hazırlayalım.":"Teklif taslaklarım"}</h2><button onClick={()=>{setOffer(null);setShowOffers(false);}} aria-label="Teklif penceresini kapat">×</button></div>{message&&<p className="market-dialog-feedback" role="status">{message}</p>}{offer?<form className="market-form" onSubmit={saveOffer}><p>{offer.title}</p><p className="market-form-note">İlan fiyatı: {tl(offer.price)} · {sellers[offer.sellerId]?.name}</p><div className="offer-presets">{[.95,.9,.85].map(r=><button key={r} type="button" onClick={()=>setAmount(Math.max(1,Math.round(offer.price*r)))}>{tl(Math.max(1,Math.round(offer.price*r)))}</button>)}</div><label>Teklifin (TL)<input name="amount" type="number" required min="1" max={offer.price} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>Satıcıya notun<textarea name="note" maxLength={400} rows={3} placeholder="Merhaba, ürünle ilgileniyorum…"/></label><button className="market-primary" disabled={!loaded||sending}>{sending?"Gönderiliyor…":live?"Teklifimi satıcıya gönder":"Teklif taslağını sakla"}</button><p className="market-form-note">{live?"Teklif bir mesaj olarak iletilir; ödeme alınmaz ve ürün otomatik ayrılmaz.":"Bu işlem satıcıya mesaj göndermez ve ürünü ayırmaz. Taslağını yalnızca bu cihazda saklar."}</p></form>:local.offers.length?<div className="offer-draft-list">{local.offers.map(o=><div key={o.listingId}><h3>{all.find(l=>l.id===o.listingId)?.title??"İlan artık mevcut değil"}</h3><strong>{tl(o.amount)}</strong><p>{o.note}</p><button onClick={()=>persist({...local,offers:local.offers.filter(x=>x.listingId!==o.listingId)})}>Taslağı kaldır</button></div>)}</div>:<div className="market-empty"><h3>İlk teklifine yer var.</h3><p>Akıştaki bir ürün için teklif taslağı oluşturabilirsin.</p></div>}</div></dialog>
  </div>;
}
